### ISSUE TITLE
Initial Build

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-oracle-source#1]

**Comment by trong-le** [comment]
Created a read stream of rows coming in. Had to create a [new aries data branch](https://github.com/aries-data/aries-data/tree/oracle) modifying the Dockerfile since oracle needs some things installed for it to actually connect [can be found here under Installation](https://github.com/oracle/node-oracledb). Current problem: Knex pulls from the same oracle repo above which only returns 100 rows at the moment. will be looking into that.

**Comment by ryw** [comment]
no more work on aries
